### ISSUE TITLE
ImportError: cannot import name 'basestring' from 'selenium.webdriver.remote.switch_to' 

### ISSUE THREAD

**Issue by bencko** [Yyonging/asyncselenium#1]
i have installed asynselenuim and selenium. And i am got an error: ImportError: cannot import name 'basestring' from 'selenium.webdriver.remote.switch_to' 
Please, tell me whats happen.

**Comment by Yyonging** [comment]
> i have installed asynselenuim and selenium. And i am got an error: ImportError: cannot import name 'basestring' from 'selenium.webdriver.remote.switch_to' Please, tell me whats happen.

what's your python version and selenium version?

**Comment by bencko** [comment]
sorry. Not actual

**Comment by eniocc** [comment]
I'm using python 3.9.1 and the same error is appears.

`ImportError: cannot import name 'basestring' from 'selenium.webdriver.remote.switch_to'`
